name: sync-fork
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: { }
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Sync to Upstream Repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with: 
          upstream_repo: https://github.com/Aptos-NFT-Lending/aptos-app-client.git
          upstream_branch: main
          downstream_branch: main
